---
title: "BIOS 611 Project Report"
author: "Jose S. Lopez"
date: "11/25/2021"
output: html_document
---

# Introduction

While corresponding experts of a product have provided reviews for many years, reviews being provided by laypeople have become the new norm in the digital era. Multiple platforms have been conducive for the average individual to provide their opinions. Social media platforms for example allow individuals and laypeople to post about their opinions about a movie. However, there are also movie, tv, and streaming specific websites that center around reviews like Rotten Tomatoes and IMDB. In fact, IMDB is the movie review website from which the data we use is derived from. From a academic research perspective there has an explosion of rich data that has come from the movie industry.

> The motion picture industry has become fertile ground for the application of new product forecasting and prerelease market evaluation models given the high stakes and high risks in producing and marketing a movie, with only three or four out of ten breaking even, and around one in ten becoming profitable at the box office. (Peng, Gui, and Li 2013).

High risks and high stakes coupled with the increasing amount of money the movie industry has been accumulating means there is room to advance and develop statistical methodology that is also applicable. Past research has previously shown that movie review "ratings are associated with movie performance, as measured by both movie revenues and viewer satisfaction" (Moon, Bergey, and Iacobucci 2010). Here we focus on exploration of a horror movie data set and consider an application of k-nearest neighbor (KNN) to predict whether a horror movie will be considered good or bad.

# Dataset Description

The data used in this analysis is derived from IMDB, was put on Kaggle and then hosted on https://github.com/rfordatascience/tidytuesday where I sourced the data from. The data contains information on 3,328 different horror movies. Examples of included properties are genre(s), release date, release country, MPAA rating, and movie run time (in minutes). The data consists of 12 columns, 11 of which pertain to movie properties, and the remaining 1 column pertains to what is considered the outcome in the analysis - the review rating (which ranged from 1 to 10).

The data set was not without missing data and columns of data that needed modification in order to be used for analysis. To begin all observations that had a missing review ratings were removed as it is our outcome of interest. Furthermore, we further subset the data set to include movies whose release country is the United States of America (USA) and whose budget was either missing or was in USA currency. Many movies had multiple genres, so we created a sub_genre variable whose value was the second listed genre of the movie. If the movie only had horror listed as their genre they the sub genre was given the value 'Pure' to indicate that is is pure horror. Another variable was created to created to enumerate the genres for each movie. A usable date variable was derived from the release date variable. Month and year variables were also created.

# Analysis Procedures



# Discussion

While there was little determined from this analysis there is much to be explored using the data set. For example the plot variable could be text mined for common words among all plot values. We could then use this variable as feature in the prediction model. The plot variable also contains the director of movies so that could be used as an index for whether a particular movie will be reviewed based on their past history. The same could be done using the cast variable except you apply indices for the cast of the movie. Furthermore, different algorithms could be better suited for prediction. 

# References

Moon, S., Bergey, P. K., & Iacobucci, D. (2010). Dynamic Effects among Movie Ratings, Movie Revenues, and Viewer Satisfaction. Journal of Marketing, 74(1), 108–121. http://www.jstor.org/stable/20619083

Peng, L., Cui, G., & Li, C. (2013). The Comparative Impact of Critics and Consumers: Applying the Generalisability Theory to Online Movie Ratings. International Journal of Market Research, 55(3), 413–436. https://doi.org/10.2501/IJMR-2013-037
